from .__ import __
from .add import add
from .all import all
from .compose import compose
from .curry import curry
from .curryN import curryN
from .pipe import pipe
from .reduce import reduce
from .reverse import reverse
from .slice import slice
from .tail import tail
